language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
deploy:
  provider: heroku
  app: http4kbin
  api_key:
    secure: iKozEosZZBocr4v7P4C4Yfzc+NpDjVrFOxWein8WiOHMqj74S/5fjSokvXjkfJHxhBRLTUmILcplEK8EKtTk0PmeZrOSkONqMvd8+87IMgNU+my09waBW7UUbD6JQm4ffWCc73lAE+sfnjta+niZrIZG+gKEVru2f9eiYe2bRF4brDDLooWko63eRPXZhHv9iGo8s40OgvbEWkjyZSzt7Iy77cJVu6Si1tJTMEMIT0n2JtlY7lJ4puCiPKJ/YUJKNzmoPbSyXMAVsZiUNbp7xhvgt1Z7Znp7i74W/MM6AqCMG6zOF9kbiDYshyh2VIVdDMsN4PHJNWGyh4v3JDzhR4nCbLDMt5gHWlhVHUuUnUGB0n5o3GGOZMzqSH50MKi3GFH7KVwjVRPsWtr5bVPL03vgjitLsSz1nGUsYAjoBDJ9zsYDHffxawCde17tjf8lio2DsBTbprWWaKkXgRktqTGsG+k/fuCzlvEdnm8FnDpU1HexPMnfQFfKq7e2EHoiIaxD4a9yOKkclBc5fCjq9WsIhQ+UOTEYEW8S+mwLhidl1xqm/sCn5kMK/qOIgJjCzy6a03BTIxkSQa0C2ByjNYBQXRH5eDIn4QLpurDdiw2kgW1hU5IXJcSapU/69l0eYahFfYM+IWrXXGQDp1CWO7sT+CxvY8zDPQO0j5kHoAY=
