language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
deploy:
  provider: heroku
  app: http4kbin
  api_key:
    secure: cKfD3pI6IUaJEXINlOT9MtJl1ICQAp5EhXA9K2LlQOfXL2KhDxChjTA2V+2vzrTShFec9PZLxfQy6lIPqUMZtGA9tOz7o6aEU8QPY5LN96iHJgfjfcZyPN46fZ7qYAvP/62Vn5LzWo66Xl/UYofB69M95uNxFfFqqh3xapT2SKF4YSEScgRCM073do0jMOt6IzOIkFKi4qZy0SZ6nUGHzP+TT15OTDfndxNo2dpcFJ3w2BrdcC9Zi/EKxDHff8Co6/r06bD/2s/8Kr/hXS2bZlqJMKxDsYHiGQNEE5YfgY8vH2jS1lJNvLQ1JLowH5KB6lDNmTooUmGLdutLy4G5NpiSMOm9xIglm1sFa4rs4GnHDIiFJvBktCleNcJ3d9g/H6/NbRkuYQIGojzUXPfH3bArUICVK8PI5S0NQKLD1KHOVsW0N0z/ksea+1rbc3PJc4qVGqH2A3RyCJ0+wVhiARYUeKVNsFM7Kj5HkXJbcHjhCkNgjUPJVCMR0MNL53A5GX1MakSYJPZ/QN/zqHifqXWu1Gd/5jus4978NeagMYrUe22Tg2dVzJH9MzhI9Ejka1lAitlkuZQtTvoaPkblT/o8wCEgfOnTe07+kVp2mrePG+WF8cSaA6y7EUdI3ffxeZmvltERDW83LNbQHBrFjPIGsBSCWCccf/2mZ9E5ywA=
